version: '3'

services:
  api:
    build: ./gamification
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gamification:/usr/src/gamification
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev.db
  front:
    build: ./bobromania
    command: npm run serve
    ports:
      - 8080:8080
    volumes:
      - ./bobromania:/app

volumes:
  postgres_data:
