# Generated by Django 3.2.8 on 2021-11-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20211113_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='min_profit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='write_off',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
