# Generated by Django 3.2.8 on 2021-11-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20211117_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_participants', models.PositiveIntegerField()),
                ('unlucky_participants', models.IntegerField()),
                ('lucky_participants', models.IntegerField()),
                ('usage_probability', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_items', to='calculator.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_items', to='calculator.product')),
            ],
        ),
    ]
