# Generated by Django 3.2.8 on 2021-11-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_bingo_discount_discountofproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingo',
            options={'ordering': ('name',)},
        ),
    ]
