# Generated by Django 3.2.8 on 2021-11-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_auto_20211123_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingodiscount',
            name='unlucky_participants',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
